nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs

npmScopes:
  fortawesome:
    npmRegistryServer: 'https://npm.fontawesome.com/'
    npmAuthToken: '${FONT_AWESOME_PRO_TOKEN}'

  yagro-ltd:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAlwaysAuth: true
    npmAuthToken: '${YAGRO_LTD_TOKEN}'
